title: Mohammad Jaminur Islam
description: Research and teaching portfolio of Mohammad Jaminur Islam, a Computer Science Ph.D. student at UC Riverside.
author: Mohammad Jaminur Islam
email: misla056@ucr.edu
baseurl: ""
url: "https://mohammadjaminur.github.io"
permalink: pretty

scholar_url: "https://scholar.google.com/citations?user=0ZT0aVkAAAAJ&hl=en"
cv_url: "https://drive.google.com/file/d/18CKHeC-sq4pQrYvi4UITygYFcalRQIZM/view?usp=sharing"
github_url: "https://github.com/mohammadjaminur"
linkedin_url: "https://www.linkedin.com/in/mohammad-jaminur-islam-684a82b2/"

markdown: kramdown
highlighter: rouge
